export const SET_USER = 'SET_USER';
export const SET_USER_REQUESTED = 'SET_USER_REQUESTED';

export const CHECK_KEPLR_REQUESTED = 'CHECK_KEPLR_REQUESTED';

export const KEPLR_GET_BALANCES_SUCCESS = 'KEPLR_GET_BALANCES_SUCCESS';

export const KEPLR_SIGN_OUT = 'KEPLR_SIGN_OUT';

export const SHOW_HIDDEN_TOKEN_BALANCE_REQUESTED = 'SHOW_HIDDEN_TOKEN_BALANCE_REQUESTED';

export const SHOW_HIDDEN_TOKEN_BALANCE_SUCCESS = 'SHOW_HIDDEN_TOKEN_BALANCE_SUCCESS';
export const SHOW_HIDDEN_TOKEN_BALANCE_ERROR = 'SHOW_HIDDEN_TOKEN_BALANCE_ERROR';

export const TERMINATE_USER_WEBSOCKET_REQUESTED = 'TERMINATE_USER_WEBSOCKET_REQUESTED';

export const REFRESH_BALANCE_FOR_TOKEN_REQUESTED = 'REFRESH_BALANCE_FOR_TOKEN_REQUESTED';
export const REFRESH_BALANCE_FOR_SIENNA = 'REFRESH_BALANCE_FOR_SIENNA';

export const REFRESH_REWARDS_BALANCES = 'REFRESH_REWARDS_BALANCES';

export const SET_AVAILABLE_REWARDS_REQUESTED = 'SET_AVAILABLE_REWARDS';
export const SET_AVAILABLE_REWARDS_SUCCESS = 'SET_AVAILABLE_REWARDS_SUCCESS';
export const SET_AVAILABLE_REWARDS_ERROR = 'SET_AVAILABLE_REWARDS_ERROR';

export const SET_AVAILABLE_BALANCE_TO_WITHDRAW_FROM_REWARDS_POOL_REQUESTED =
  'SET_AVAILABLE_BALANCE_TO_WITHDRAW_FROM_REWARDS_POOL';
export const SET_AVAILABLE_BALANCE_TO_WITHDRAW_FROM_REWARDS_POOL_SUCCESS =
  'SET_AVAILABLE_BALANCE_TO_WITHDRAW_FROM_REWARDS_POOL_SUCCESS';
export const SET_AVAILABLE_BALANCE_TO_WITHDRAW_FROM_REWARDS_POOL_ERROR =
  'SET_AVAILABLE_BALANCE_TO_WITHDRAW_FROM_REWARDS_POOL_ERROR';
