import { rgba } from 'polished';
import { breakpoints } from './breakpoints';

export const defaultColors = {
  primary: '#28282E',
  swapBlue: '#2070CC',
  lendBlue: '#375D8D',
  stableBlue: '#212C3A',
  disabledBlue: '#d2e2f5',
  white: '#F9F9F9',
  dark: '#28282E',
  green: '#20CC7A',
  orange: '#FDA003',
  red: '#CC203F',
  ash: '#413e65',
  blackStone20: '#F9F9F9',
  blackStone25: '#F5F5F5',
  blackStone30: '#EAEAEA',
  blackStone40: '#BFBFC0',
  blackStone50: '#949497',
  blackStone60: '#69696D',
  blackStone70: '#3E3E43',
  blackStone80: '#28282E',
  blackStone90: '#202024',
};

const colors = {
  primary: defaultColors.primary,
  swapBlue: defaultColors.swapBlue,
  lendBlue: defaultColors.lendBlue,
  stableBlue: defaultColors.stableBlue,
  disabledBlue: defaultColors.disabledBlue,
  light: defaultColors.white,
  lightShade: rgba(defaultColors.white, 0.75),
  dark: defaultColors.dark,
  darkShade: rgba(defaultColors.dark, 0.75),
  ash: defaultColors.ash,
  bg: defaultColors.white,
  bgInverted: defaultColors.blackStone80,
  border: rgba(defaultColors.ash, 0.115),
  shadow: rgba(defaultColors.ash, 0.175),
  heading: defaultColors.primary,
  text: defaultColors.primary,
  textInverted: defaultColors.white,
  warning: defaultColors.orange,
  danger: defaultColors.red,
  success: defaultColors.green,
  infoText: defaultColors.blackStone60,
  swapInfoText: defaultColors.blackStone40,
  swapStepText: defaultColors.blackStone30,
  dividerLine: defaultColors.blackStone30,
  dividerLineInverted: defaultColors.blackStone70,
  button: defaultColors.blackStone20,
  leftMenu: 'white',

  modes: {
    dark: {
      primary: defaultColors.primary,
      swapBlue: defaultColors.swapBlue,
      lendBlue: defaultColors.lendBlue,
      stableBlue: defaultColors.stableBlue,
      disabledBlue: defaultColors.disabledBlue,
      light: defaultColors.white,
      lightShade: rgba(defaultColors.white, 0.75),
      dark: defaultColors.dark,
      darkShade: rgba(defaultColors.dark, 0.75),
      ash: defaultColors.ash,
      bg: defaultColors.blackStone90,
      bgInverted: defaultColors.white,
      border: rgba(defaultColors.ash, 0.115),
      shadow: rgba(defaultColors.ash, 0.175),
      heading: defaultColors.white,
      text: defaultColors.white,
      textInverted: defaultColors.primary,
      warning: defaultColors.orange,
      danger: defaultColors.red,
      success: defaultColors.green,
      infoText: defaultColors.blackStone40,
      swapInfoText: defaultColors.blackStone40,
      swapStepText: defaultColors.blackStone80,
      dividerLine: defaultColors.blackStone70,
      dividerLineInverted: defaultColors.blackStone30,
      button: defaultColors.blackStone90,
      leftMenu: defaultColors.primary,
    },
  },
};
const theme = {
  initialColorModeName: 'light',
  colors,
  //space: [0, 4, 8, 16, 32, 64, 128, 256, 512],
  breakpoints: {
    xs: `${breakpoints.xs}px`,
    sm: `${breakpoints.sm}px`,
    md: `${breakpoints.md}px`,
    lg: `${breakpoints.lg}px`,
    xl: `${breakpoints.xl}px`,
  },
};

export type ThemeType = typeof theme;
export default theme;
